import 'controller/home_verification_popup_controller.dart';import 'package:flutter/material.dart';import 'package:mustard_ng/core/app_export.dart';import 'package:mustard_ng/widgets/custom_button.dart';import 'package:mustard_ng/widgets/custom_icon_button.dart';
// ignore_for_file: must_be_immutable
class HomeVerificationPopupBottomsheet extends StatelessWidget {HomeVerificationPopupBottomsheet(this.controller);

HomeVerificationPopupController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.end, children: [Align(alignment: Alignment.centerLeft, child: SingleChildScrollView(child: Container(decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.customBorderTL50), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.start, children: [GestureDetector(onTap: () {onTapImgClose();}, child: Padding(padding: getPadding(left: 24, top: 42, right: 24), child: CommonImageView(svgPath: ImageConstant.imgClose, height: getSize(30.00), width: getSize(30.00)))), CustomIconButton(height: 90, width: 90, margin: getMargin(left: 24, top: 78, right: 24), shape: IconButtonShape.CircleBorder45, padding: IconButtonPadding.PaddingAll31, alignment: Alignment.center, child: CommonImageView(svgPath: ImageConstant.imgLock90X90)), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 24, top: 38, right: 24), child: Text("msg_let_s_get_you_v".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoBold28Black900.copyWith(height: 1.00)))), Align(alignment: Alignment.center, child: Container(width: getHorizontalSize(239.00), margin: getMargin(left: 24, top: 16, right: 24), child: Text("msg_you_can_verify".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtLatoRegular16Black900.copyWith(height: 1.50)))), CustomButton(width: 380, text: "lbl_verify_now".tr, margin: getMargin(left: 24, top: 47, right: 24, bottom: 20), onTap: onTapBtnVerifynow, alignment: Alignment.center)]))))]))); } 
onTapImgClose() { Get.back(); } 
onTapBtnVerifynow() { Get.toNamed(AppRoutes.emailVerificationScreen); } 
 }
