import '../send_money_bank_transfer_bank_search_two_bottomsheet/widgets/listaccessbanklog_item_widget.dart';import 'controller/send_money_bank_transfer_bank_search_two_controller.dart';import 'models/listaccessbanklog_item_model.dart';import 'package:flutter/material.dart';import 'package:mustard_ng/core/app_export.dart';import 'package:mustard_ng/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class SendMoneyBankTransferBankSearchTwoBottomsheet extends StatelessWidget {SendMoneyBankTransferBankSearchTwoBottomsheet(this.controller);

SendMoneyBankTransferBankSearchTwoController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.end, children: [Align(alignment: Alignment.centerLeft, child: SingleChildScrollView(child: Container(decoration: AppDecoration.fillWhiteA700, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(left: 33, top: 27, right: 33), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.max, children: [GestureDetector(onTap: () {onTapImgClose();}, child: Padding(padding: getPadding(top: 1, bottom: 3), child: CommonImageView(svgPath: ImageConstant.imgClose19X15, height: getSize(15.00), width: getSize(15.00)))), Padding(padding: getPadding(left: 120), child: Text("lbl_beneficiaries".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoBold20.copyWith(height: 1.00)))]))), Container(height: getVerticalSize(1.00), width: getHorizontalSize(428.00), margin: getMargin(top: 9), decoration: BoxDecoration(color: ColorConstant.gray50)), CustomSearchView(width: 380, focusNode: FocusNode(), controller: controller.inputController, hintText: "msg_search_benefici".tr, margin: getMargin(left: 24, top: 14, right: 24), alignment: Alignment.center, prefix: Container(margin: getMargin(left: 18, top: 16, right: 6, bottom: 16), child: CommonImageView(svgPath: ImageConstant.imgSearch)), prefixConstraints: BoxConstraints(minWidth: getSize(15.00), minHeight: getSize(15.00))), Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(left: 24, top: 28, right: 24), child: Text("msg_send_to_benefic".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtLatoBold20.copyWith(height: 1.00)))), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 24, top: 15, right: 19, bottom: 302), child: Obx(() => ListView.builder(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, itemCount: controller.sendMoneyBankTransferBankSearchTwoModelObj.value.listaccessbanklogItemList.length, itemBuilder: (context, index) {ListaccessbanklogItemModel model = controller.sendMoneyBankTransferBankSearchTwoModelObj.value.listaccessbanklogItemList[index]; return ListaccessbanklogItemWidget(model);}))))]))))]))); } 
onTapImgClose() { Get.back(); } 
 }
